# Generated by Django 4.1.2 on 2023-02-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboarding', '0003_rename_employeecode_resource_empcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='Role',
            field=models.CharField(choices=[('software engineer', 'Software Engineer'), ('senior software engineer', ' Senior Software Engineer')], default='software engineer', max_length=100),
        ),
    ]
