# Generated by Django 4.1.2 on 2023-02-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboarding', '0004_alter_resource_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='Billed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='Grade',
            field=models.CharField(choices=[('3.0', '3.0'), ('3.1', '3.1'), ('3.2', '3.2'), ('3.3', '3.3'), ('5.1', '5.1'), ('5.2', '5.2'), ('5.3', '5.3'), ('7.1', '7.1'), ('7.2', '7.2')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='Location',
            field=models.CharField(choices=[('Pune', 'Pune'), ('Bengaluru', 'Bengaluru'), ('Nagpur', 'Nagpur'), ('Bengaluru SEZ', 'Bengaluru SEZ')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='Role',
            field=models.CharField(choices=[('Software Engineer', 'Software Engineer'), ('Senior Software Engineer', 'Senior Software Engineer'), ('Senior Quality Engineer', 'Senior Quality Engineer'), ('Lead Software Engineer', 'Lead Software Engineer'), ('Lead Quality Engineer', 'Lead Quality Engineer'), ('Engineering Lead', 'Engineering Lead'), ('Engineering Lead - Quality', 'Engineering Lead - Quality'), ('Senior Engineering Lead', 'Senior Engineering Lead'), ('Senior Engineering Lead - Quality', 'Senior Engineering Lead - Quality'), ('Project Lead', 'Project Lead'), ('Project Lead - Quality', 'Project Lead - Quality'), ('Architect', 'Architect'), ('Contract Consultant', 'Contract Consultant')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='Status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=100),
        ),
    ]
