# Generated by Django 4.2.1 on 2023-05-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboarding', '0007_alter_resource_empcode_alter_resource_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='EmpCode',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='Location',
            field=models.CharField(choices=[('Pune', 'Pune'), ('Bengaluru', 'Bengaluru'), ('Nagpur', 'Nagpur'), ('Bengaluru SEZ', 'Bengaluru SEZ')], max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='Role',
            field=models.CharField(choices=[('Software Engineer', 'Software Engineer'), ('Senior Software Engineer', 'Senior Software Engineer'), ('Senior Quality Engineer', 'Senior Quality Engineer (3.2)'), ('Lead Software Engineer', 'Lead Software Engineer (3.3)'), ('Lead Quality Engineer', 'Lead Quality Engineer (3.3)'), ('Engineering Lead', 'Engineering Lead (5.1)'), ('Engineering Lead - Quality', 'Engineering Lead - Quality (5.1)'), ('Senior Engineering Lead', 'Senior Engineering Lead (5.2)'), ('Senior Engineering Lead - Quality', 'Senior Engineering Lead - Quality (5.2)'), ('Project Lead', 'Project Lead (5.3)'), ('Project Lead - Quality', 'Project Lead - Quality (5.3)'), ('Architect', 'Architect (7.1)'), ('Contract Consultant', 'Contract Consultant')], max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='SowRoles',
            field=models.CharField(choices=[('Engineer (SDE1)', 'Engineer (SDE1)'), ('Senior Engineer (SDE2)', 'Senior Engineer (SDE2)'), ('Senior Engineer (SDE3)', 'Senior Engineer (SDE3)'), ('Quality Engineer (SDET1)', 'Quality Engineer (SDET1)'), ('QE Automation', 'QE Automation'), ('QE Automation Lead', 'QE Automation Lead'), ('Quality Lead (SDE2)', 'Quality Lead (SDE2)')], max_length=50),
        ),
    ]
