# Generated by Django 4.2.1 on 2023-06-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboarding', '0009_alter_resource_role_alter_resource_sowroles'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='Project',
            field=models.CharField(choices=[('SG:SFDF', 'SG:SFDF'), ('JOSYS', 'JOSYS')], default=' ', max_length=100),
        ),
    ]
